model:
  name: SimpleDetection
  type: yolov6-n
  pretrained:
  params:
    n_classes: null

  additional_heads:
    - name: SegmentationHead
      params:
        n_classes: null
      loss: 
        name: FocalLoss
        params:

dataset:
  local_path: /home/klemen/luxonis/model_debug/datasets/coco-2017-person