model:
  name: AdvancedDetectionSegmentation
  type: yolov6-n
  pretrained:
  params:
    n_classes: null

  additional_heads:
    - name: SegmentationHead
      params:
        n_classes: null
      loss: 
        name: FocalLoss
        params:

dataset:
  # team_id: luxonis_team_id # TODO
  # dataset_id: 649fc9f39b1845dd49e393c2 # TODO
  bucket_type: aws
  team_id: 2af31474-a342-49c9-8fa4-786ac83a43a3
  dataset_id: 64a079d8028d6439d136495d

train:
  preprocessing:
    train_image_size: [512,512]
  
  train_metrics_interval: 100
  validation_interval: 10
  
  optimizers:
    optimizer:
      name: SGD
      params:
        lr: 0.02
        momentum: 0.937
        nesterov: True
        weight_decay: 0.0005
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 100
        eta_min: 0
        
  losses:
    log_sub_losses: True
    weights: [0.1, 1]
    
