model:
  name: SimpleDetection
  type: yolov6-n
  pretrained:
  params:
    n_classes: null

dataset:
  local_path: /home/klemen/luxonis/model_debug/datasets/coco-2017-person #(string)

train:
  batch_size: 4