# model:
#   name: SimpleDetection
#   type: yolov6-n
#   pretrained:
#   params:
#     n_classes: null
#     is_4head: False

model:
  name: aceaquatec
  type: #YoloV6-n # uncomment this to use predefined model
  pretrained: False
  params: # only take into account if using predefined model

  backbone:
    name: EfficientRep
    pretrained:
    params:
      channels_list: [64, 128, 256, 512, 1024]
      num_repeats: [1, 6, 12, 18, 6]
      depth_mul: 0.33
      width_mul: 0.25

  neck:
    name: RepPANNeck
    params:
      channels_list: [256, 128, 128, 256, 256, 512]
      num_repeats: [12, 12, 12, 12]
      depth_mul: 0.33
      width_mul: 0.25

  heads:
    - name: IKeypoint
      params:
        n_classes: 1
        n_keypoints: 17 #7
        anchors:
          - [12,16, 19,36, 40,28]  # P3/8
          - [36,75, 76,55, 72,146]  # P4/16
          - [142,110, 192,243, 459,401]  # P5/32
      loss:
        name: YoloV7PoseLoss
        params:

dataset:
  team_id: 2af31474-a342-49c9-8fa4-786ac83a43a3 #luxonis_team_id #luxonis # TODO
  dataset_id: 64a079d8028d6439d136495d #coco_sample_people  # TODO
  bucket_type: aws

logger:
  is_wandb: False 
  wandb_entity: luxonis
  project_name: ml-ops-train
  project_id: null #19
  is_mlflow: False #True

train:
  callbacks:
    test_on_finish: False #True
    export_on_finish: False #True

tuner:
  params:
    train.optimizers.optimizer.name_categorical: ["Adam", "SGD"]
    train.optimizers.optimizer.params.lr_float: [0.0001, 0.001]
    train.batch_size_int: [4, 16, 4]

exporter:
  export_weights: #/home/klemen/luxonis/models/output/1-black-impala/best_val_metric/map=0.0271_loss=2.1368_39_SimpleDetection.ckpt
  export_model_name: test-model-3
  onnx:
    opset_version: 12 # opset version of onnx used (int)
    dynamic_axes: null # define if dynamic input shapes are used (dict)
  openvino:
    active: False # bool if export to openvino (bool)
  blobconverter:
    active: False # bool if export to blob (bool)
    shaves: 6 # number of shaves used (int)
  s3_upload:
    active: True # bool if upload .ckpt, .onnx and config file to s3 bucket (bool)
    # bucket: luxonis-test-bucket # name of the s3 bucket (string)
    # upload_directory: luxonis-train # location of directory for upload (string)