model:
  name: SimpleDetection
  type: yolov6-n
  pretrained:
  params:
    n_classes: null
    is_4head: False

dataset:
  team_name: luxonis # TODO
  dataset_name: coco_sample_people  # TODO

logger:
  is_wandb: False 
  wandb_entity: luxonis
  project_name: ml-ops-train
  is_mlflow: True
  mlflow_tracking_uri: https://ml-track.luxonis.com

tuner:
  train.optimizers.optimizer.name_categorical: ["Adam", "SGD"] #["Adam", "SGD"]
  train.optimizers.optimizer.params.lr_float: [0.0001, 0.001]
  train.batch_size_int: [4, 16, 4]