model:
  name: SimpleSegmentation
  type: 
  pretrained:
  
  backbone:
    name: ContextSpatial #ResNet18
    pretrained:

  heads:
    - name: BiSeNetHead #SegmentationHead
      params:
        n_classes: null
      loss: 
        name: FocalLoss
        params:

dataset:
  team_name: luxonis # TODO
  dataset_name: ppsr # TODO