model:
  name: SimpleClassification
  type:
  pretrained:

  backbone:
    name: MicroNet
    pretrained:

  heads:
    - name: ClassificationHead
      params:
        n_classes: null
      loss: 
        name: CrossEntropyLoss
        params:

dataset:
  local_path: /home/klemen/luxonis/model_debug/datasets/coco-2017-person