model:
  name: SimpleDetection
  type: yolov6-n
  pretrained:
  params:
    n_classes: null
    is_4head: False

dataset:
  team_name: luxonis # TODO
  dataset_name: coco_sample_all #coco_sample_people # TODO

logger:
  is_wandb: False 
  wandb_entity: luxonis
  project_name: ml-ops-train