model:
  name: SimpleSegmentation
  type: 
  pretrained: output/7-teal-vicuna/min_val_loss/val_loss=0.0000_val_mIoU=0.0000_epoch=12_SimpleSegmentation.ckpt
  backbone:
    name: ResNet18
    pretrained:

  heads:
    - name: SegmentationHead
      params:
        n_classes: null
      loss: 
        name: FocalLoss
        params:

dataset:
  local_path: /home/klemen/test_datasets/coco_person_keypoints/ 