model:
  name: SimpleSegmentation
  type: 
  pretrained:
  
  backbone:
    name: ResNet18
    pretrained:

  heads:
    - name: SegmentationHead
      params:
        n_classes: null
      loss: 
        name: FocalLoss
        params:

dataset:
  local_path: /home/klemen/test_datasets/coco_person_keypoints/ 