model:
  name: SimpleClassification
  type:
  pretrained:

  backbone:
    name: MicroNet
    pretrained:

  heads:
    - name: ClassificationHead
      params:
        n_classes: null
      loss: 
        name: CrossEntropyLoss
        params:

dataset:
  team_id: luxonis_team_id # TODO
  dataset_id: 649fc9f39b1845dd49e393c2 # TODO
