name: Build and deploy app image

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  push-store:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PAT}}
              
      - name: Get commit name
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            
      - name: 'Build Inventory Image'
        run: |
          docker build --build-arg GITHUB_TOKEN=${{secrets.GHCR_PAT}} -f docker/Dockerfile . --tag ghcr.io/luxonis/models:latest --tag ghcr.io/luxonis/models:${{ steps.commit.outputs.sha_short }}
          docker push ghcr.io/luxonis/models --all-tags